### ISSUE TITLE
Problemer med arrays

### ISSUE THREAD

**Issue by Larsbeas** [KredeGC/Lectio-API#1]
Jeg har nu testet din php fil som ser super smart ud, men er stødt ind i et problem.
Når jeg bruger funktionen: `->get_schedule_student($gymnasie_id, $lectio_id, $unixtime)`
Og indsætter de passende variable f.eks. ($gymnasie_id="402" og $lectio_id="studentensid" og vores unixtime lyder på "1536580800".

Når jeg så prøver at hente elevens skema vha:
```
require('lectio.php');
$lectio = new lectio('simple_html_dom.php');
$schedule = $lectio->get_schedule_student($gymnasie_id, $lectio_id, $unixtime);
```

`echo $schedule['schedule'][1]['lessons'][1]['title'];`

Hvis jeg bruger echo `$schedule['schedule']` står der "Array", men jeg ved ikke hvordan jeg kan få vist indholdet inde i arrayet såsom modul navn, tid og lokale osv..

Jeg har også prøvet funktionen: 

`print_r($lectioObject->get_schedule_student($gymnasie_id, $lectio_id, $unixtime));`
Hvilket ikke giver noget resultat.

Jeg har dog prøvet funktionen:
```
echo "<pre>";
var_dump($schedule);

```
Som giver disse resultater:

```
array(7) {
  ["title"]=>
  NULL
  ["week"]=>
  int(0)
  ["year"]=>
  int(0)
  ["day"]=>
  string(0) ""
  ["weekdays"]=>
  array(0) {
  }
  ["schedule"]=>
  array(0) {
  }
  ["dayschedule"]=>
  array(0) {
  }
}

```

Det er nok mig som har lavet en fejl, da jeg er forholdvis ny til php, håber du kan hjælpe.

**Comment by KredeGC** [comment]
Jeg kan se at jeg havde glemt at opdatere koden da jeg opdaterede README filen. Det burde virke nu (selvom jeg ikke lige har testet det), så du skal nok lige downloade den igen. Når du har testet det så kom endelig tilbage og sig om det hjalp eller ej.

**Comment by Larsbeas** [comment]
Hvis du ikke har noget i mod det, vil du så oplyse din discord eller anden kontakt platform, da jeg har nogle spørgsmål til dette.

**Comment by KredeGC** [comment]
Sure, #6869, jeg har ikke vildt meget tid lige nu men du kan skive og så kan jeg svare løbende.

**Comment by Larsbeas** [comment]
Okay mange tak, det virker som det skal, men har alligvel et hurtigt spørgsmål.
Hvordan vælger man en helt specifikt array f.eks. hvis jeg skal se skemaet for i dag altså "dayschedule", men det skal kun være 1 lektion og kun navnet på modulet.
